name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: npm install
    - name: Run bootstrap
      run: npm run start
    - name: Build binaries
      run: npm run pkg

    - name: Sign and notarize the nexrender-cli-macos
      uses: toitlang/action-macos-sign-notarize@v1.1.1
      with:
        certificate: ${{ secrets.MACOS_CERTIFICATE }}
        certificate-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        username: ${{ secrets.APPLE_ID_USERNAME }}
        password: ${{ secrets.APPLE_ID_PASSWORD }}
        apple-team-id: 89QX7NXPQM
        app-path: bin/nexrender-cli-macos

    - name: Sign and notarize the nexrender-worker-macos
      uses: toitlang/action-macos-sign-notarize@v1.1.1
      with:
        certificate: ${{ secrets.MACOS_CERTIFICATE }}
        certificate-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        username: ${{ secrets.APPLE_ID_USERNAME }}
        password: ${{ secrets.APPLE_ID_PASSWORD }}
        apple-team-id: 89QX7NXPQM
        app-path: bin/nexrender-worker-macos

    - name: Publish release
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        files: bin/*
